"""Stable public contracts for the proposal-only Optimization Runtime."""

from embedded_copilot.optimization.approval.context import (
    OptimizationApprovalContext,
    optimization_approval_fingerprint,
)
from embedded_copilot.optimization.contracts import (
    OptimizationAlgorithmPort,
    OptimizationEvaluationPort,
    OptimizationPort,
    OptimizationProgressSink,
    OptimizationRegistryPort,
)
from embedded_copilot.optimization.exceptions import (
    OptimizationError,
    OptimizationProgressUnavailable,
    OptimizationRejected,
    OptimizationUnavailable,
)
from embedded_copilot.optimization.facade import OptimizationRuntime
from embedded_copilot.optimization.factory import create_optimization_runtime
from embedded_copilot.optimization.integration import project_hardware_observation
from embedded_copilot.optimization.models import (
    OptimizationAlgorithm,
    OptimizationAlgorithmMetadata,
    OptimizationApprovalDecision,
    OptimizationConstraint,
    OptimizationContextProjection,
    OptimizationEvaluationProjection,
    OptimizationEvaluationRequest,
    OptimizationEvaluationStatus,
    OptimizationFailureCode,
    OptimizationImprovement,
    OptimizationInvocationRequest,
    OptimizationMetric,
    OptimizationMetricUnit,
    OptimizationParameterChange,
    OptimizationParameterRange,
    OptimizationPlan,
    OptimizationProgressEvent,
    OptimizationProgressEventType,
    OptimizationProposal,
    OptimizationRequest,
    OptimizationResolutionRequest,
    OptimizationRiskLevel,
    OptimizationSnapshot,
    OptimizationState,
    OptimizationTarget,
    optimization_algorithm_metadata_fingerprint,
    optimization_context_fingerprint,
    optimization_evaluation_fingerprint,
    optimization_plan_fingerprint,
    optimization_proposal_fingerprint,
    optimization_request_fingerprint,
    optimization_snapshot_fingerprint,
)

__all__ = (
    "OptimizationAlgorithm",
    "OptimizationAlgorithmMetadata",
    "OptimizationAlgorithmPort",
    "OptimizationApprovalContext",
    "OptimizationApprovalDecision",
    "OptimizationConstraint",
    "OptimizationContextProjection",
    "OptimizationError",
    "OptimizationEvaluationPort",
    "OptimizationEvaluationProjection",
    "OptimizationEvaluationRequest",
    "OptimizationEvaluationStatus",
    "OptimizationFailureCode",
    "OptimizationImprovement",
    "OptimizationInvocationRequest",
    "OptimizationMetric",
    "OptimizationMetricUnit",
    "OptimizationParameterChange",
    "OptimizationParameterRange",
    "OptimizationPlan",
    "OptimizationPort",
    "OptimizationProgressEvent",
    "OptimizationProgressEventType",
    "OptimizationProgressSink",
    "OptimizationProgressUnavailable",
    "OptimizationProposal",
    "OptimizationRegistryPort",
    "OptimizationRejected",
    "OptimizationRequest",
    "OptimizationResolutionRequest",
    "OptimizationRiskLevel",
    "OptimizationRuntime",
    "OptimizationSnapshot",
    "OptimizationState",
    "OptimizationTarget",
    "OptimizationUnavailable",
    "create_optimization_runtime",
    "optimization_algorithm_metadata_fingerprint",
    "optimization_approval_fingerprint",
    "optimization_context_fingerprint",
    "optimization_evaluation_fingerprint",
    "optimization_plan_fingerprint",
    "optimization_proposal_fingerprint",
    "optimization_request_fingerprint",
    "optimization_snapshot_fingerprint",
    "project_hardware_observation",
)
