"""Framework-independent, proposal-only Firmware Engineering Layer."""

from embedded_copilot.engineering_firmware.contracts import FirmwareEngineeringPort
from embedded_copilot.engineering_firmware.exceptions import (
    FirmwareEngineeringError,
    FirmwareEngineeringRejected,
)
from embedded_copilot.engineering_firmware.facade import EngineeringFirmwareRuntime
from embedded_copilot.engineering_firmware.factory import (
    create_engineering_firmware_runtime,
)
from embedded_copilot.engineering_firmware.integration.inputs import (
    FirmwareEngineeringRequest,
)
from embedded_copilot.engineering_firmware.models import (
    BuildArtifactStatus,
    BuildProposal,
    CodeGenerationIntent,
    CodeGenerationPlan,
    DebugStrategyProposal,
    DriverDesignProposal,
    FirmwareArchitectureModule,
    FirmwareArchitectureProposal,
    FirmwareBuildArtifactType,
    FirmwareBuildSystem,
    FirmwareDiagnosticCategory,
    FirmwareDiagnosticStrategy,
    FirmwareDriverRequirement,
    FirmwareDriverType,
    FirmwareEngineeringProposal,
    FirmwareEvidenceTrace,
    FirmwareExecutionContract,
    FirmwareExecutionPrerequisite,
    FirmwareFindingCode,
    FirmwareFindingSeverity,
    FirmwareInterfaceContract,
    FirmwareInterfaceContractProposal,
    FirmwareModuleLayer,
    FirmwarePlatformProfile,
    FirmwarePlatformProjection,
    FirmwarePlatformStatus,
    FirmwarePriorityRecommendation,
    FirmwareProposalItemStatus,
    FirmwareReviewFinding,
    FirmwareReviewProjection,
    FirmwareTaskProposal,
    FirmwareTaskType,
    FirmwareToolchainRequirement,
    RTOSTaskArchitectureProposal,
    firmware_engineering_proposal_fingerprint,
    firmware_platform_fingerprint,
)

__all__ = (
    "BuildArtifactStatus",
    "BuildProposal",
    "CodeGenerationIntent",
    "CodeGenerationPlan",
    "DebugStrategyProposal",
    "DriverDesignProposal",
    "EngineeringFirmwareRuntime",
    "FirmwareArchitectureModule",
    "FirmwareArchitectureProposal",
    "FirmwareBuildArtifactType",
    "FirmwareBuildSystem",
    "FirmwareDiagnosticCategory",
    "FirmwareDiagnosticStrategy",
    "FirmwareDriverRequirement",
    "FirmwareDriverType",
    "FirmwareEngineeringError",
    "FirmwareEngineeringPort",
    "FirmwareEngineeringProposal",
    "FirmwareEngineeringRejected",
    "FirmwareEngineeringRequest",
    "FirmwareEvidenceTrace",
    "FirmwareExecutionContract",
    "FirmwareExecutionPrerequisite",
    "FirmwareFindingCode",
    "FirmwareFindingSeverity",
    "FirmwareInterfaceContract",
    "FirmwareInterfaceContractProposal",
    "FirmwareModuleLayer",
    "FirmwarePlatformProfile",
    "FirmwarePlatformProjection",
    "FirmwarePlatformStatus",
    "FirmwarePriorityRecommendation",
    "FirmwareProposalItemStatus",
    "FirmwareReviewFinding",
    "FirmwareReviewProjection",
    "FirmwareTaskProposal",
    "FirmwareTaskType",
    "FirmwareToolchainRequirement",
    "RTOSTaskArchitectureProposal",
    "create_engineering_firmware_runtime",
    "firmware_engineering_proposal_fingerprint",
    "firmware_platform_fingerprint",
)
