"""Framework-independent controlled tool execution runtime."""

from embedded_copilot.tool_runtime.exceptions import ToolAuditUnavailable
from embedded_copilot.tool_runtime.factory import create_tool_runtime
from embedded_copilot.tool_runtime.models import (
    BuildStatus,
    CompileFirmwareArguments,
    FirmwareBuildOutput,
    FirmwareTestOutput,
    ReadSerialLogArguments,
    RunFirmwareTestArguments,
    SerialLogLine,
    SerialLogOutput,
    SerialSeverity,
    SerialSeverityCount,
    SerialSourceType,
    ToolAdapterResult,
    ToolArtifactReference,
    ToolAuditEvent,
    ToolAuditEventType,
    ToolBuildSystem,
    ToolCompiler,
    ToolExecutionContext,
    ToolMetric,
    ToolMetricUnit,
    ToolPermissionDecision,
    ToolPermissionReason,
    ToolPermissionStatus,
    ToolRequest,
    ToolResult,
    ToolResultStatus,
    tool_request_fingerprint,
)
from embedded_copilot.tool_runtime.ports import (
    EngineeringToolPort,
    ToolAuditSink,
    ToolExecutionPort,
    ToolPermissionPort,
)
from embedded_copilot.tool_runtime.runtime import ToolRuntime

__all__ = (
    "BuildStatus",
    "CompileFirmwareArguments",
    "EngineeringToolPort",
    "FirmwareBuildOutput",
    "FirmwareTestOutput",
    "ReadSerialLogArguments",
    "RunFirmwareTestArguments",
    "SerialLogLine",
    "SerialLogOutput",
    "SerialSeverity",
    "SerialSeverityCount",
    "SerialSourceType",
    "ToolAdapterResult",
    "ToolArtifactReference",
    "ToolAuditEvent",
    "ToolAuditEventType",
    "ToolAuditSink",
    "ToolAuditUnavailable",
    "ToolBuildSystem",
    "ToolCompiler",
    "ToolExecutionContext",
    "ToolExecutionPort",
    "ToolMetric",
    "ToolMetricUnit",
    "ToolPermissionDecision",
    "ToolPermissionPort",
    "ToolPermissionReason",
    "ToolPermissionStatus",
    "ToolRequest",
    "ToolResult",
    "ToolResultStatus",
    "ToolRuntime",
    "create_tool_runtime",
    "tool_request_fingerprint",
)
