"""Framework-independent embedded debug observation runtime."""

from embedded_copilot.debug_runtime.exceptions import (
    DebugAuditUnavailable,
    DebugObservationRejected,
    DebugObservationTimeout,
    DebugSourceUnavailable,
)
from embedded_copilot.debug_runtime.models import (
    DebugAuditEvent,
    DebugAuditEventType,
    DebugInsight,
    DebugReasoningContext,
    DebugSeverity,
    DebugSnapshotRequest,
    DebugSourceCapture,
    DebugSourceType,
    FrozenDebugSnapshot,
    RegisterObservation,
    RegisterRecord,
    StackFrameObservation,
    StackFrameRecord,
    TargetIdentificationRequest,
    TargetIdentity,
    TelemetryMetric,
    TelemetryRequest,
    TelemetrySnapshot,
    TelemetryUnit,
    UARTLogRecord,
    UARTObservation,
)
from embedded_copilot.debug_runtime.ports import (
    DebugAuditSink,
    DebugPort,
    DebugSourcePort,
)
from embedded_copilot.debug_runtime.runtime import DebugRuntime, create_debug_runtime

__all__ = (
    "DebugAuditEvent",
    "DebugAuditEventType",
    "DebugAuditSink",
    "DebugAuditUnavailable",
    "DebugInsight",
    "DebugObservationRejected",
    "DebugObservationTimeout",
    "DebugPort",
    "DebugReasoningContext",
    "DebugRuntime",
    "DebugSeverity",
    "DebugSnapshotRequest",
    "DebugSourceCapture",
    "DebugSourcePort",
    "DebugSourceType",
    "DebugSourceUnavailable",
    "FrozenDebugSnapshot",
    "RegisterObservation",
    "RegisterRecord",
    "StackFrameObservation",
    "StackFrameRecord",
    "TargetIdentificationRequest",
    "TargetIdentity",
    "TelemetryMetric",
    "TelemetryRequest",
    "TelemetrySnapshot",
    "TelemetryUnit",
    "UARTLogRecord",
    "UARTObservation",
    "create_debug_runtime",
)
