"""Framework-independent Embedded Copilot Product Layer."""

from embedded_copilot.product.contracts import ProductWorkspacePort
from embedded_copilot.product.exceptions import ProductError, ProductProjectionRejected
from embedded_copilot.product.facade import ProductRuntime
from embedded_copilot.product.factory import create_product_runtime
from embedded_copilot.product.integration.core import (
    CreateProjectRequest,
    create_project_request_fingerprint,
)
from embedded_copilot.product.models import (
    DashboardStageProjection,
    EngineeringDashboardProjection,
    EngineeringReleaseReport,
    EngineeringReleaseSection,
    EngineeringTimelineEvent,
    EngineeringTimelineProjection,
    EngineeringWorkspace,
    ProductDecisionOutcome,
    ProductDecisionProjection,
    ProductReference,
    ProductReferenceType,
    ProductStage,
    ProductStageReference,
    ProductStageStatus,
    ProductTimelineEventType,
    ProjectSession,
    ReviewDashboardProjection,
    canonical_product_json,
    dashboard_stage_fingerprint,
    engineering_dashboard_fingerprint,
    engineering_release_report_fingerprint,
    engineering_workspace_fingerprint,
    product_decision_fingerprint,
    product_reference_fingerprint,
    product_stage_reference_fingerprint,
    project_session_fingerprint,
    release_section_fingerprint,
    review_dashboard_fingerprint,
    timeline_event_fingerprint,
    timeline_projection_fingerprint,
)

__all__ = (
    "CreateProjectRequest",
    "DashboardStageProjection",
    "EngineeringDashboardProjection",
    "EngineeringReleaseReport",
    "EngineeringReleaseSection",
    "EngineeringTimelineEvent",
    "EngineeringTimelineProjection",
    "EngineeringWorkspace",
    "ProductDecisionOutcome",
    "ProductDecisionProjection",
    "ProductError",
    "ProductProjectionRejected",
    "ProductReference",
    "ProductReferenceType",
    "ProductRuntime",
    "ProductStage",
    "ProductStageReference",
    "ProductStageStatus",
    "ProductTimelineEventType",
    "ProductWorkspacePort",
    "ProjectSession",
    "ReviewDashboardProjection",
    "canonical_product_json",
    "create_product_runtime",
    "create_project_request_fingerprint",
    "dashboard_stage_fingerprint",
    "engineering_dashboard_fingerprint",
    "engineering_release_report_fingerprint",
    "engineering_workspace_fingerprint",
    "product_decision_fingerprint",
    "product_reference_fingerprint",
    "product_stage_reference_fingerprint",
    "project_session_fingerprint",
    "release_section_fingerprint",
    "review_dashboard_fingerprint",
    "timeline_event_fingerprint",
    "timeline_projection_fingerprint",
)
