"""Framework-independent human review and revision proposal boundary."""

from embedded_copilot.human_loop.contracts import (
    DesignProposalPort,
    FeedbackProjectionPort,
    HumanLoopPort,
    HumanLoopProgressSink,
    HumanReviewPort,
)
from embedded_copilot.human_loop.exceptions import (
    FeedbackProjectionUnavailable,
    HumanLoopError,
    HumanLoopProgressUnavailable,
    HumanLoopRejected,
    HumanReviewUnavailable,
    RevisionProposalUnavailable,
)
from embedded_copilot.human_loop.facade import HumanLoopRuntime
from embedded_copilot.human_loop.factory import create_human_loop_runtime
from embedded_copilot.human_loop.models import (
    FeedbackPriority,
    FeedbackProjection,
    FeedbackProjectionRequest,
    HumanLoopProgressEvent,
    HumanLoopProgressEventType,
    HumanLoopState,
    HumanReviewDecision,
    HumanReviewDecisionProjection,
    HumanReviewRequest,
    HumanReviewSnapshot,
    HumanReviewSubmissionRequest,
    ProposalProjection,
    ProposalResolutionRequest,
    RevisionChange,
    RevisionContext,
    RevisionContextReference,
    RevisionContextSource,
    RevisionGenerationRequest,
    RevisionPreparationRequest,
    RevisionProposal,
    feedback_projection_fingerprint,
    human_review_decision_fingerprint,
    human_review_snapshot_fingerprint,
    proposal_projection_fingerprint,
    revision_context_fingerprint,
    revision_proposal_fingerprint,
)
from embedded_copilot.human_loop.review.request import project_proposal_projection

__all__ = (
    "DesignProposalPort",
    "FeedbackPriority",
    "FeedbackProjection",
    "FeedbackProjectionPort",
    "FeedbackProjectionRequest",
    "FeedbackProjectionUnavailable",
    "HumanLoopError",
    "HumanLoopPort",
    "HumanLoopProgressEvent",
    "HumanLoopProgressEventType",
    "HumanLoopProgressSink",
    "HumanLoopProgressUnavailable",
    "HumanLoopRejected",
    "HumanLoopRuntime",
    "HumanLoopState",
    "HumanReviewDecision",
    "HumanReviewDecisionProjection",
    "HumanReviewPort",
    "HumanReviewRequest",
    "HumanReviewSnapshot",
    "HumanReviewSubmissionRequest",
    "HumanReviewUnavailable",
    "ProposalProjection",
    "ProposalResolutionRequest",
    "RevisionChange",
    "RevisionContext",
    "RevisionContextReference",
    "RevisionContextSource",
    "RevisionGenerationRequest",
    "RevisionPreparationRequest",
    "RevisionProposal",
    "RevisionProposalUnavailable",
    "create_human_loop_runtime",
    "feedback_projection_fingerprint",
    "human_review_decision_fingerprint",
    "human_review_snapshot_fingerprint",
    "project_proposal_projection",
    "proposal_projection_fingerprint",
    "revision_context_fingerprint",
    "revision_proposal_fingerprint",
)
