"""Framework-independent Agent Execution Layer."""

from embedded_copilot.agent_execution.contracts import (
    AgentCapabilityBinding,
    AgentExecutionBoundaryPort,
    AgentExecutionPort,
    AgentRegistryPort,
    ExecutionProgressSink,
    ExecutionVerificationPort,
)
from embedded_copilot.agent_execution.exceptions import (
    AgentExecutionError,
    AgentExecutionRejected,
    ExecutionProgressUnavailable,
    ExecutionRecoveryRejected,
)
from embedded_copilot.agent_execution.factory import create_agent_execution_runtime
from embedded_copilot.agent_execution.facade import AgentExecutionRuntime
from embedded_copilot.agent_execution.models import (
    AgentBindingMetadata,
    AgentExecutionInputContext,
    AgentExecutionRequest,
    AgentExecutionResult,
    AgentExecutionResultStatus,
    AgentExecutionSnapshot,
    AgentExecutionState,
    AgentInvocationRequest,
    AgentResolutionRequest,
    ExecutionApprovalContext,
    ExecutionApprovalDecision,
    ExecutionArtifactReference,
    ExecutionContextReference,
    ExecutionContextSourceType,
    ExecutionFailureCode,
    ExecutionMetric,
    ExecutionMetricUnit,
    ExecutionProgressEvent,
    ExecutionResultProjection,
    ExecutionVerificationRequest,
    ExecutionVerificationResult,
    ExecutionVerificationStatus,
    agent_binding_fingerprint,
    agent_execution_result_fingerprint,
    agent_execution_snapshot_fingerprint,
    execution_verification_result_fingerprint,
)

__all__ = (
    "AgentBindingMetadata",
    "AgentCapabilityBinding",
    "AgentExecutionBoundaryPort",
    "AgentExecutionError",
    "AgentExecutionInputContext",
    "AgentExecutionPort",
    "AgentExecutionRejected",
    "AgentExecutionRequest",
    "AgentExecutionResult",
    "AgentExecutionResultStatus",
    "AgentExecutionRuntime",
    "AgentExecutionSnapshot",
    "AgentExecutionState",
    "AgentInvocationRequest",
    "AgentRegistryPort",
    "AgentResolutionRequest",
    "ExecutionApprovalContext",
    "ExecutionApprovalDecision",
    "ExecutionArtifactReference",
    "ExecutionContextReference",
    "ExecutionContextSourceType",
    "ExecutionFailureCode",
    "ExecutionMetric",
    "ExecutionMetricUnit",
    "ExecutionProgressEvent",
    "ExecutionProgressSink",
    "ExecutionProgressUnavailable",
    "ExecutionRecoveryRejected",
    "ExecutionResultProjection",
    "ExecutionVerificationPort",
    "ExecutionVerificationRequest",
    "ExecutionVerificationResult",
    "ExecutionVerificationStatus",
    "agent_binding_fingerprint",
    "agent_execution_result_fingerprint",
    "agent_execution_snapshot_fingerprint",
    "create_agent_execution_runtime",
    "execution_verification_result_fingerprint",
)
