"""Framework-independent controlled Execution Integration Layer."""

from embedded_copilot.execution_runtime.approval.context import (
    ExecutionApprovalContext,
    execution_approval_fingerprint,
)
from embedded_copilot.execution_runtime.contracts import (
    ExecutionExecutorPort,
    ExecutionExecutorRegistryPort,
    ExecutionPort,
    ExecutionProgressSink,
    ExecutionVerificationPort,
)
from embedded_copilot.execution_runtime.exceptions import (
    ExecutionError,
    ExecutionProgressUnavailable,
    ExecutionRejected,
    ExecutionTimeout,
    ExecutionUnavailable,
    ExecutionVerificationFailed,
)
from embedded_copilot.execution_runtime.facade import ExecutionRuntime
from embedded_copilot.execution_runtime.factory import create_execution_runtime
from embedded_copilot.execution_runtime.integration.agent_execution import (
    project_agent_execution_snapshot,
)
from embedded_copilot.execution_runtime.models import (
    ExecutionArtifactReference,
    ExecutionContextProjection,
    ExecutionExecutorMetadata,
    ExecutionExecutorResolutionRequest,
    ExecutorType,
    ExecutionFailureCode,
    ExecutionInvocationRequest,
    ExecutionMetric,
    ExecutionMetricUnit,
    ExecutionPlan,
    ExecutionPreparationRequest,
    ExecutionProgressEvent,
    ExecutionProgressEventType,
    ExecutionProposalReference,
    ExecutionResultProjection,
    ExecutionResultStatus,
    ExecutionSnapshot,
    ExecutionState,
    ExecutionVerificationProjection,
    ExecutionVerificationRequest,
    ExecutionVerificationStatus,
    execution_context_fingerprint,
    execution_executor_metadata_fingerprint,
    execution_plan_fingerprint,
    execution_result_fingerprint,
    execution_snapshot_fingerprint,
    execution_verification_fingerprint,
)

__all__ = (
    "ExecutionApprovalContext",
    "ExecutionArtifactReference",
    "ExecutionContextProjection",
    "ExecutionError",
    "ExecutionExecutorMetadata",
    "ExecutionExecutorPort",
    "ExecutionExecutorRegistryPort",
    "ExecutionExecutorResolutionRequest",
    "ExecutionFailureCode",
    "ExecutionInvocationRequest",
    "ExecutionMetric",
    "ExecutionMetricUnit",
    "ExecutionPlan",
    "ExecutionPort",
    "ExecutionPreparationRequest",
    "ExecutionProgressEvent",
    "ExecutionProgressEventType",
    "ExecutionProgressSink",
    "ExecutionProgressUnavailable",
    "ExecutionProposalReference",
    "ExecutionRejected",
    "ExecutionResultProjection",
    "ExecutionResultStatus",
    "ExecutionRuntime",
    "ExecutionSnapshot",
    "ExecutionState",
    "ExecutionTimeout",
    "ExecutionUnavailable",
    "ExecutionVerificationFailed",
    "ExecutionVerificationPort",
    "ExecutionVerificationProjection",
    "ExecutionVerificationRequest",
    "ExecutionVerificationStatus",
    "ExecutorType",
    "create_execution_runtime",
    "execution_approval_fingerprint",
    "execution_context_fingerprint",
    "execution_executor_metadata_fingerprint",
    "execution_plan_fingerprint",
    "execution_result_fingerprint",
    "execution_snapshot_fingerprint",
    "execution_verification_fingerprint",
    "project_agent_execution_snapshot",
)
