"""Framework-independent, projection-only Hardware Validation Layer."""

from embedded_copilot.engineering_validation.contracts import (
    DeviceEvidencePort,
    HardwareValidationPort,
)
from embedded_copilot.engineering_validation.exceptions import (
    HardwareValidationError,
    HardwareValidationRejected,
)
from embedded_copilot.engineering_validation.facade import HardwareValidationRuntime
from embedded_copilot.engineering_validation.factory import (
    create_hardware_validation_runtime,
)
from embedded_copilot.engineering_validation.integration.inputs import (
    HardwareValidationRequest,
)
from embedded_copilot.engineering_validation.models import (
    AcquisitionStatus,
    DeviceEvidenceCollectionRequest,
    DeviceEvidenceCollectionResult,
    DigitalTwinComponentState,
    DigitalTwinStateProjection,
    EvidenceAnalysisProjection,
    EvidenceAnalysisResult,
    EvidenceMetricUnit,
    EvidenceOutcome,
    EvidenceQualification,
    EvidenceRecord,
    EvidenceSafeMetadata,
    EvidenceSnapshot,
    EvidenceSourceType,
    EvidenceType,
    HILValidationItem,
    HILValidationProjection,
    HardwareValidationReport,
    ProjectionState,
    TestPlanProposal,
    ValidationAnalysisStatus,
    ValidationEvidenceTrace,
    ValidationFindingCode,
    ValidationFindingSeverity,
    ValidationReviewFinding,
    ValidationReviewProjection,
    ValidationTestPlanItem,
    ValidationTestType,
    device_evidence_collection_request_fingerprint,
    device_evidence_collection_result_fingerprint,
    evidence_record_fingerprint,
    evidence_safe_metadata_fingerprint,
    evidence_snapshot_fingerprint,
    hardware_validation_report_fingerprint,
    test_plan_proposal_fingerprint,
    validation_test_plan_item_fingerprint,
)

__all__ = (
    "AcquisitionStatus",
    "DeviceEvidenceCollectionRequest",
    "DeviceEvidenceCollectionResult",
    "DeviceEvidencePort",
    "DigitalTwinComponentState",
    "DigitalTwinStateProjection",
    "EvidenceAnalysisProjection",
    "EvidenceAnalysisResult",
    "EvidenceMetricUnit",
    "EvidenceOutcome",
    "EvidenceQualification",
    "EvidenceRecord",
    "EvidenceSafeMetadata",
    "EvidenceSnapshot",
    "EvidenceSourceType",
    "EvidenceType",
    "HILValidationItem",
    "HILValidationProjection",
    "HardwareValidationError",
    "HardwareValidationPort",
    "HardwareValidationRejected",
    "HardwareValidationReport",
    "HardwareValidationRequest",
    "HardwareValidationRuntime",
    "ProjectionState",
    "TestPlanProposal",
    "ValidationAnalysisStatus",
    "ValidationEvidenceTrace",
    "ValidationFindingCode",
    "ValidationFindingSeverity",
    "ValidationReviewFinding",
    "ValidationReviewProjection",
    "ValidationTestPlanItem",
    "ValidationTestType",
    "create_hardware_validation_runtime",
    "device_evidence_collection_request_fingerprint",
    "device_evidence_collection_result_fingerprint",
    "evidence_record_fingerprint",
    "evidence_safe_metadata_fingerprint",
    "evidence_snapshot_fingerprint",
    "hardware_validation_report_fingerprint",
    "test_plan_proposal_fingerprint",
    "validation_test_plan_item_fingerprint",
)
