"""Read-only Knowledge Intelligence Layer public contracts."""

from embedded_copilot.knowledge.intelligence.exceptions import (
    KnowledgeDataRejected,
    KnowledgeGraphRejected,
    KnowledgeIntelligenceError,
    KnowledgeMemoryBridgeRejected,
    KnowledgeObservationTimeout,
    KnowledgeSourceUnavailable,
)
from embedded_copilot.knowledge.intelligence.facade import (
    KnowledgeIntelligenceRuntime,
)
from embedded_copilot.knowledge.intelligence.factory import (
    create_knowledge_intelligence_runtime,
)
from embedded_copilot.knowledge.intelligence.models import (
    DatasheetKnowledgeRequest,
    EngineeringKnowledgeRequest,
    FailureRuleCandidate,
    FrozenKnowledgeGraphSnapshot,
    KnowledgeEntityType,
    KnowledgeFailureSeverity,
    KnowledgeGraphEntity,
    KnowledgeGraphEvidenceProjection,
    KnowledgeGraphProjectionRequest,
    KnowledgeGraphQuery,
    KnowledgeGraphRelationship,
    KnowledgeIntelligenceResult,
    KnowledgeProgressTrace,
    KnowledgeProvenance,
    KnowledgeRelationshipCandidate,
    KnowledgeRelationshipType,
    KnowledgeSourceCandidate,
    KnowledgeSourceType,
    KnowledgeVerificationMethod,
    KnowledgeVerificationOutcome,
    KnowledgeVerificationStatus,
    MemoryBridgeProjection,
    MemoryBridgeRequest,
    SourceTrustCatalog,
    SourceTrustEntry,
    SourceTrustLevel,
    VerifiedKnowledgeEvidence,
)
from embedded_copilot.knowledge.intelligence.ports import (
    KnowledgeIntelligencePort,
    KnowledgeVerificationPort,
    WebResearchSourcePort,
)

__all__ = (
    "DatasheetKnowledgeRequest",
    "EngineeringKnowledgeRequest",
    "FailureRuleCandidate",
    "FrozenKnowledgeGraphSnapshot",
    "KnowledgeDataRejected",
    "KnowledgeEntityType",
    "KnowledgeFailureSeverity",
    "KnowledgeGraphEntity",
    "KnowledgeGraphEvidenceProjection",
    "KnowledgeGraphProjectionRequest",
    "KnowledgeGraphQuery",
    "KnowledgeGraphRejected",
    "KnowledgeGraphRelationship",
    "KnowledgeIntelligenceError",
    "KnowledgeIntelligencePort",
    "KnowledgeIntelligenceResult",
    "KnowledgeIntelligenceRuntime",
    "KnowledgeMemoryBridgeRejected",
    "KnowledgeObservationTimeout",
    "KnowledgeProgressTrace",
    "KnowledgeProvenance",
    "KnowledgeRelationshipCandidate",
    "KnowledgeRelationshipType",
    "KnowledgeSourceCandidate",
    "KnowledgeSourceType",
    "KnowledgeSourceUnavailable",
    "KnowledgeVerificationMethod",
    "KnowledgeVerificationOutcome",
    "KnowledgeVerificationPort",
    "KnowledgeVerificationStatus",
    "MemoryBridgeProjection",
    "MemoryBridgeRequest",
    "SourceTrustCatalog",
    "SourceTrustEntry",
    "SourceTrustLevel",
    "VerifiedKnowledgeEvidence",
    "WebResearchSourcePort",
    "create_knowledge_intelligence_runtime",
)
