"""Browser-facing Embedded Copilot Web API boundary."""

from embedded_copilot.web_api.app import create_web_api_app
from embedded_copilot.web_api.contracts import (
    WebAttachmentProjectionPort,
    WebBuildApprovalPort,
    WebBuildResultRepositoryPort,
    WebFirmwareProposalRepositoryPort,
    WebObservationProjectionPort,
    WebProjectPreparationPort,
    WebProjectRepositoryPort,
)
from embedded_copilot.web_api.exceptions import (
    WebApiError,
    WebDependencyUnavailable,
    WebProjectNotFound,
    WebRequestRejected,
)
from embedded_copilot.web_api.models import (
    WebAttachmentMetadataRequest,
    WebAttachmentProjection,
    WebAttachmentProjectionRequest,
    WebAttachmentType,
    WebBuildResultProjection,
    WebBuildStartRequest,
    WebChatRequest,
    WebChatResponse,
    WebDashboardProjection,
    WebErrorResponse,
    WebFeedbackRequest,
    WebFirmwareGenerateRequest,
    WebProjectCreateRequest,
    WebProjectDetail,
    WebProjectReference,
    WebReportProjection,
    WebReportSection,
    WebReviewProjection,
    WebStage,
    WebStageProjection,
    WebStageStatus,
    WebTimelineEventProjection,
    WebTimelineProjection,
    canonical_web_json,
    web_attachment_fingerprint,
)

__all__ = (
    "WebApiError",
    "WebAttachmentMetadataRequest",
    "WebAttachmentProjection",
    "WebAttachmentProjectionPort",
    "WebAttachmentProjectionRequest",
    "WebAttachmentType",
    "WebBuildApprovalPort",
    "WebBuildResultProjection",
    "WebBuildResultRepositoryPort",
    "WebBuildStartRequest",
    "WebChatRequest",
    "WebChatResponse",
    "WebDashboardProjection",
    "WebDependencyUnavailable",
    "WebErrorResponse",
    "WebFeedbackRequest",
    "WebFirmwareGenerateRequest",
    "WebFirmwareProposalRepositoryPort",
    "WebObservationProjectionPort",
    "WebProjectCreateRequest",
    "WebProjectDetail",
    "WebProjectNotFound",
    "WebProjectPreparationPort",
    "WebProjectReference",
    "WebProjectRepositoryPort",
    "WebReportProjection",
    "WebReportSection",
    "WebRequestRejected",
    "WebReviewProjection",
    "WebStage",
    "WebStageProjection",
    "WebStageStatus",
    "WebTimelineEventProjection",
    "WebTimelineProjection",
    "canonical_web_json",
    "create_web_api_app",
    "web_attachment_fingerprint",
)
