"""Framework-independent Hardware Intelligence Layer."""

from embedded_copilot.hardware_intelligence.contracts import (
    DigitalTwinProviderPort,
    HardwareIntelligencePort,
    HardwareProgressSink,
    HardwareTelemetryPort,
    HardwareValidationPort,
)
from embedded_copilot.hardware_intelligence.exceptions import (
    HardwareIntelligenceError,
    HardwareIntelligenceRejected,
    HardwareIntelligenceUnavailable,
    HardwareObservationRejected,
    HardwareProgressUnavailable,
    HardwareValidationUnavailable,
)
from embedded_copilot.hardware_intelligence.facade import (
    HardwareIntelligenceRuntime,
)
from embedded_copilot.hardware_intelligence.factory import (
    create_hardware_intelligence_runtime,
)
from embedded_copilot.hardware_intelligence.integration.execution import (
    project_execution_snapshot,
)
from embedded_copilot.hardware_intelligence.models import (
    DigitalTwinMetric,
    DigitalTwinProjection,
    DigitalTwinRequest,
    HILProjection,
    HILProjectionStatus,
    HardwareAnalysisRequest,
    HardwareContextProjection,
    HardwareFailureCode,
    HardwareIntelligenceSnapshot,
    HardwareIntelligenceState,
    HardwareMetadata,
    HardwareMetricUnit,
    HardwareObservation,
    HardwareProgressEvent,
    HardwareProgressEventType,
    HardwareTelemetryRequest,
    HardwareValidationApproval,
    HardwareValidationDecision,
    HardwareValidationProjection,
    HardwareValidationRequest,
    HardwareValidationStatus,
    HardwareValidationType,
    digital_twin_fingerprint,
    hardware_context_fingerprint,
    hardware_observation_fingerprint,
    hardware_snapshot_fingerprint,
    hardware_validation_approval_fingerprint,
    hardware_validation_fingerprint,
    hil_projection_fingerprint,
)

__all__ = (
    "DigitalTwinMetric",
    "DigitalTwinProjection",
    "DigitalTwinProviderPort",
    "DigitalTwinRequest",
    "HILProjection",
    "HILProjectionStatus",
    "HardwareAnalysisRequest",
    "HardwareContextProjection",
    "HardwareFailureCode",
    "HardwareIntelligenceError",
    "HardwareIntelligencePort",
    "HardwareIntelligenceRejected",
    "HardwareIntelligenceRuntime",
    "HardwareIntelligenceSnapshot",
    "HardwareIntelligenceState",
    "HardwareIntelligenceUnavailable",
    "HardwareMetadata",
    "HardwareMetricUnit",
    "HardwareObservation",
    "HardwareObservationRejected",
    "HardwareProgressEvent",
    "HardwareProgressEventType",
    "HardwareProgressSink",
    "HardwareProgressUnavailable",
    "HardwareTelemetryPort",
    "HardwareTelemetryRequest",
    "HardwareValidationApproval",
    "HardwareValidationDecision",
    "HardwareValidationPort",
    "HardwareValidationProjection",
    "HardwareValidationRequest",
    "HardwareValidationStatus",
    "HardwareValidationType",
    "HardwareValidationUnavailable",
    "create_hardware_intelligence_runtime",
    "digital_twin_fingerprint",
    "hardware_context_fingerprint",
    "hardware_observation_fingerprint",
    "hardware_snapshot_fingerprint",
    "hardware_validation_approval_fingerprint",
    "hardware_validation_fingerprint",
    "hil_projection_fingerprint",
    "project_execution_snapshot",
)
